### ISSUE TITLE
Gigs assigned by Admin don't show up in User profiles

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#84]
![screen shot 2017-12-04 at 4 21 05 pm](https://user-images.githubusercontent.com/31675533/33583437-490b0818-d90f-11e7-946e-23b3da2a7a52.png)
![screen shot 2017-12-04 at 4 21 16 pm](https://user-images.githubusercontent.com/31675533/33583438-49645710-d90f-11e7-987d-358260d2039b.png)

**Comment by cjairm** [comment]
@baranskiy David asked the same thing (this error is made by humans)... This is because as musician must to "ask to make my profile visible", and to fix this problem you need to do this.

1.-Go to admin dashboard, and hide his/her profile from public
2.-Go to musician dashboard, and "ask to make my profile visible"
3.-Return to admin dashboard, and make it visible.

And you will have the others actions that you have not now, such as, percent bar, payments, payouts, calendar
