### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by ghost** [DavelBM/test.bemusical.us#85]
All this (and more) happened to me the first time I tried booking a gig. So I went back and tried recreating the same path and record the issues. Watch the entire video to see all the issues:

1. Can't submit the higher quote.
2. Resubmitting a smaller quote takes me to a place that says "this token is already taken"
3. The client didn't get a confirmation email. 
4. Can't log in as a client even though I am already registered as Clien3

https://drive.google.com/open?id=1QRaVfSLGL5CkBFYb1t8O82YtwOHggKwa

Previously I was able to log into the client's account and the requested gig would show up here but when I clicked on it the error message would show up.

**Comment by cjairm** [comment]
Okay.. this is a complicated thing... I will try to explain step by step

You could not "sent" the quote because in the improvement #82 David ask to send a text message to the client where musician already sent a quote....

In our previous bugs, for some reason, we were not saving correctly the info of clients. Now we are doing good, but with c2@davelsound.com, and roman+c3@bemusic.al something happened. I had to delete from the database those clients. Actually, I want to ask you guys @DavelBM @baranskiy if you can confirm you phone number (While I was typing, I decided to make this action error-proof, so never mind I fixed).

Okay... We were in the submitting musician bug.

All in all, you sent the quote, but the program just fail when it tried to send the text-message (because in the code we try to send a message to client not to "new requester", but I add something to sent the message if you are or are not a client). That's why re-submit fails. The send_text_message code is just before send_email_code, so send_text_message failed could not continue with send_email_code. 

You could not log because there where problems, but they are solved now

**Comment by cjairm** [comment]
Checked @baranskiy
